project:
  type: book
  output-dir: _book

book:
  title: "R pour la science des données (2e éd.)"
  reader-mode: true

  page-footer:
    left: |
      R for Data Science (2e éd.) a été crit par Hadley Wickham, Mine
      Çetinkaya-Rundel et Garrett Grolemund.
      Traduit en français par Alba Maiques.
    right: |
      Ce livre a été conçu avec <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.jpg
  favicon: cover.jpg
  site-url: https://fr.r4ds.hadley.nz/
  repo-url: https://github.com/AlbaMqs/r4ds-french
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd

    - preface-2e.qmd
    - intro.qmd

    - part: whole-game.qmd
      chapters:
        - data-visualize.qmd
        - workflow-basics.qmd
        - data-transform.qmd
        - workflow-style.qmd
        - data-tidy.qmd
        - workflow-scripts.qmd
        - data-import.qmd
        - workflow-help.qmd

    - part: visualize.qmd
      chapters:
        - layers.qmd
        - EDA.qmd
        - communication.qmd

    - part: transform.qmd
      chapters:
        - logicals.qmd
        - numbers.qmd
        - strings.qmd
        - regexps.qmd
        - factors.qmd
        - datetimes.qmd
        - missing-values.qmd
        - joins.qmd

    - part: import.qmd
      chapters:
        - spreadsheets.qmd
        - databases.qmd
        - arrow.qmd
        - rectangling.qmd
        - webscraping.qmd

    - part: program.qmd
      chapters:
        - functions.qmd
        - iteration.qmd
        - base-R.qmd

    - part: communicate.qmd
      chapters:
        - quarto.qmd
        - quarto-formats.qmd

format:
  html:
    theme:
      - cosmo
      - r4ds.scss
    code-link: true

    author-meta: "Hadley Wickham, Mine Çetinkaya-Rundel et Garrett Grolemund"
    translator: "Alba Maiques"
    include-in-header: "plausible.html"
    callout-appearance: simple

editor: visual

