# Bienvenue {.unnumbered}

Ce site est la traduction française de la seconde édition de "**R for Data Science**" (R4DS : R pour la science des données) par Hadley Wickhame, Mine Çetinkaya-Rundel et Garrett Grolemund.
Cet ouvrage vous apprendra les rudiments de la science des données avec R.
Vous apprendrez à utiliser vos données dans R afin de les structurer de manière optimale, de les transformer et de les visualiser.

Dans ce livre, vous trouverez un recueil de compétences pratiques pour la science des données.
Tout comme un chimiste apprend à nettoyer des éprouvettes et à approvisionner un laboratoire, vous apprendrez à nettoyer des données et à réaliser des graphiques — et bien d'autres choses encore.
Il s'agit des compétences qui permettent à la science des données de se concrétiser, et ici, vous découvrirez les meilleures pratiques pour chacune de ces tâches avec R.
Vous apprendrez à manier la grammaire des graphiques, à écrire des programmes lisibles et à réaliser des manipulations reproductibles afin de gagner du temps.
Vous apprendrez également à structurer votre pensées afin de faciliter la manipulation, la visualisation et l'exploration des données.

Ce site est et sera toujours gratuit sous licence [CC BY-NC-ND 3.0](https://creativecommons.org/licenses/by-nc-nd/3.0/us/).
Si vous appréciez cet ouvrage gratuit et que vous souhaitez faire une don afin de remercier ses auteurs, vous pouvez la faire à l'association [Kākāpō Recovery](https://www.doc.govt.nz/kakapo-donate): le [kākāpō](https://www.youtube.com/watch?v=9T1vfsHYiKY) (présent sur la couverture de l'édition anglaise de R4DS) est une espèce de perroquets endémique en Nouvelle-Zélande.
Il s'agit d'une espèce en danger critique d'extinction dont il ne reste que 248 individus.

## Note de la traductrice

Cette traduction a été réalisée bénévolement et sur son temps libre par Alba Maiques.
Si elle essaie de se rapprocher au mieux des mots des auteurs originaux, certaines expression ou formulation ont dûes être modiifiées afin de faciliter leur compréhension en français.
Par conséquence, elle peut présenter quelques déviation de l'oeuvre originale critiquable ou quelques coquilles.
Auquel cas, vous êtes invité·e à faire remonter sur le [GitHub du projet](https://github.com/AlbaMqs/r4ds-french).

Une version physique payante de l'édition anglaise de cette ouvrage est disponible sur [Amazon](http://amzn.to/2aHLAQ1).
Celle-ci ainsi que d'autres traduction de la première édition peuvent être trouvées sur le site :

-   [Anglais (2nd éd.)](http://r4ds.hadley.nz)
-   [Espagnol (1ere éd.)](http://es.r4ds.hadley.nz)
-   [Italien (1ere éd.)](https://it.r4ds.hadley.nz)
-   [Turc (1ere éd.)](https://tr.r4ds.hadley.nz)

Vous pourrez également trouver des suggestions de réponses aux exercices sur le site <https://mine-cetinkaya-rundel.github.io/r4ds-solutions> (en anglais).

Notez que R4DS se conforme au [Contributor Code of Conduct](#0).
En contribuant à cet ouvrage, vous devez également vous conformer à ses conditions.
